language: node_js
node_js:
- '0.10'
before_script: npm install -g karma-cli
deploy:
  provider: openshift
  user: in3pi287@gmail.com
  password:
    secure: U50sC8Sm2NKas5CiecPftu+NM4Y8xu1UEAHfoLoQpgKK6MnXLYZjPC0i/qmbigv40nvBu9t+xdbpUbGuOO12A8UASLIcGMIyeMCcN9yU+Ud4jJsANeR0lecSn10syRtHw2QGEY/AEXnxNau+IWh6zQ10Rl9Zn9/MEHG9mffpyHQ=
  app: citest2
  domain: fideltest
  on:
    repo: intrepido/CI-Test2
